baseURL = "https://goonline.dev"
languageCode = "en-us"
title = "Go Online"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = "268170783"
  google_tag_manager_id = ""

  [params.homepage]
    show_call_box = true
    hide_view_all_services = false  # set to true to hide the View All Services button

  [params.logo]
    mobile = "images/logo/goonline.svg"
    mobile_height = "80px"
    desktop = "images/logo/goonline.svg"
    desktop_height = "100px"
    alt = "Go Online - Web Solutions"

  [params.homepage_meta_tags]
    meta_description = "Get your business online with go online. We provide web development and support services to grow your presence online in this fastest-growing technology era."
    meta_og_title = "Go Online"
    meta_og_type = "website"
    meta_og_url = "https://goonline.dev"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
    meta_og_description = "Get your business online with go online. We provide web development and support services to grow your presence online in this fastest-growing technology era."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

  [params.team]
    summary_large_truncate = 120  # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = 'Copyright © 2021. All Rights Reserved | Designed By <a class="zerostatic" href="https://goonline.dev/services">GoOnline Development</a>'

[menu]
  # Main Menu
[[menu.main]]
      name = "About"
      url = "/about/"
      weight = 1

  [[menu.main]]
    name = "Services"
    url = "/services/"
      weight = 2

  [[menu.main]]
      name = "Team"
      url = "/team/"
      weight = 3

  [[menu.main]]
      name = "Contact"
      url = "/contact/"
      weight = 4
  
  [[menu.main]]
      name = "Pricing"
      url = "/pricing/"
      weight = 5

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
      name = "About"
      url = "/about/"
      weight = 2

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
      weight = 3
